// Certificate data
const certificatesData = [
    {
        id: 'rhcsa-001',
        title: 'Red Hat Certified System Administrator',
        issuer: 'Red Hat',
        issuerLogo: 'assets/logos/redhat.png',
        issuerUrl: 'https://www.redhat.com/en/services/certification/rhcsa',
        date: '2023-06-15',
        description: 'The Red Hat Certified System Administrator (RHCSA) certification validates the knowledge and skills needed to perform the core system administration tasks required in Red Hat Enterprise Linux environments.',
        credentialId: 'RH12345678',
        verifyUrl: 'https://www.redhat.com/rhtapps/certification/verify/?certId=RH12345678',
        category: 'System Administration',
        categoryIcon: 'ri-server-line',
        featured: true,
        hours: 120,
        skills: ['Linux', 'Bash', 'Networking', 'Security', 'Troubleshooting'],
        image: 'assets/certificates/certificates.jpg'
    },
    {
        id: 'aws-sa-001',
        title: 'AWS Certified Solutions Architect - Associate',
        issuer: 'Amazon Web Services',
        issuerLogo: 'assets/logos/aws.png',
        issuerUrl: 'https://aws.amazon.com/certification/certified-solutions-architect-associate/',
        date: '2023-03-21',
        description: 'The AWS Certified Solutions Architect - Associate examination validates technical expertise in designing and deploying scalable, highly available, and fault-tolerant systems on AWS.',
        credentialId: 'AWS00123456',
        verifyUrl: 'https://aws.amazon.com/verification',
        category: 'Cloud Computing',
        categoryIcon: 'ri-cloud-line',
        featured: true,
        hours: 80,
        skills: ['AWS', 'Cloud Architecture', 'Security', 'Networking', 'Database'],
        image: 'assets/certificates/certificates.jpg'
    },
    {
        id: 'react-001',
        title: 'Advanced React and Redux',
        issuer: 'Udemy',
        issuerLogo: 'assets/logos/udemy.png',
        issuerUrl: 'https://www.udemy.com/',
        date: '2022-11-30',
        description: 'Comprehensive course covering advanced React concepts, Redux, and modern front-end development practices for building complex, state-driven applications.',
        credentialId: 'UC-123456789',
        verifyUrl: 'https://www.udemy.com/certificate/UC-123456789/',
        category: 'Web Development',
        categoryIcon: 'ri-code-s-slash-line',
        featured: false,
        hours: 40,
        skills: ['React', 'Redux', 'JavaScript', 'Frontend', 'Web Development'],
        image: 'assets/certificates/certificates.jpg'
    },
    {
        id: 'node-001',
        title: 'Complete Node.js Developer',
        issuer: 'Zero To Mastery Academy',
        issuerLogo: 'assets/logos/ztm.png',
        issuerUrl: 'https://zerotomastery.io/',
        date: '2022-09-10',
        description: 'Comprehensive Node.js course covering building RESTful APIs, authentication, database integration, testing, and deployment of Node.js applications.',
        credentialId: 'ZTM12345',
        verifyUrl: 'https://academy.zerotomastery.io/verify/ZTM12345',
        category: 'Web Development',
        categoryIcon: 'ri-code-s-slash-line',
        featured: false,
        hours: 45,
        skills: ['Node.js', 'Express', 'MongoDB', 'REST API', 'JavaScript'],
        image: 'assets/certificates/certificates.jpg'
    },
    {
        id: 'cyber-001',
        title: 'Cybersecurity Fundamentals',
        issuer: 'Coursera',
        issuerLogo: 'assets/logos/coursera.png',
        issuerUrl: 'https://www.coursera.org/',
        date: '2022-07-05',
        description: 'Fundamental principles of cybersecurity including threat detection, encryption, network security, and best practices for protecting systems and data from various attacks.',
        credentialId: 'CRSE9876543',
        verifyUrl: 'https://www.coursera.org/verify/CRSE9876543',
        category: 'Cybersecurity',
        categoryIcon: 'ri-shield-keyhole-line',
        featured: false,
        hours: 30,
        skills: ['Network Security', 'Encryption', 'Risk Management', 'Threat Analysis'],
        image: 'assets/certificates/certificates.jpg'
    },
    {
        id: 'docker-001',
        title: 'Docker and Kubernetes: The Complete Guide',
        issuer: 'Udemy',
        issuerLogo: 'assets/logos/udemy.png',
        issuerUrl: 'https://www.udemy.com/',
        date: '2022-05-18',
        description: 'Comprehensive course on containerization with Docker and orchestration with Kubernetes, including multi-container deployments and CI/CD integration.',
        credentialId: 'UC-987654321',
        verifyUrl: 'https://www.udemy.com/certificate/UC-987654321/',
        category: 'DevOps',
        categoryIcon: 'ri-terminal-box-line',
        featured: true,
        hours: 50,
        skills: ['Docker', 'Kubernetes', 'Containerization', 'DevOps', 'CI/CD'],
        image: 'assets/certificates/certificates.jpg'
    },
    {
        id: 'tensorflow-001',
        title: 'TensorFlow Developer Specialization',
        issuer: 'DeepLearning.AI',
        issuerLogo: 'assets/logos/deeplearning.png',
        issuerUrl: 'https://www.deeplearning.ai/',
        date: '2022-02-28',
        description: 'Comprehensive program covering the fundamentals of machine learning with TensorFlow, building and training neural networks, and implementing computer vision and NLP models.',
        credentialId: 'DLAI789456',
        verifyUrl: 'https://www.coursera.org/account/accomplishments/specialization/DLAI789456',
        category: 'Artificial Intelligence',
        categoryIcon: 'ri-brain-line',
        featured: false,
        hours: 70,
        skills: ['TensorFlow', 'Machine Learning', 'Neural Networks', 'Computer Vision', 'NLP'],
        image: 'assets/certificates/certificates.jpg'
    },
    {
        id: 'pentest-001',
        title: 'Ethical Hacking and Penetration Testing',
        issuer: 'Offensive Security',
        issuerLogo: 'assets/logos/offensive-security.png',
        issuerUrl: 'https://www.offensive-security.com/',
        date: '2021-11-12',
        description: 'Advanced course on ethical hacking methodologies, penetration testing techniques, and security vulnerability assessment used by security professionals.',
        credentialId: 'OS123987',
        verifyUrl: 'https://www.offensive-security.com/verify/OS123987',
        category: 'Cybersecurity',
        categoryIcon: 'ri-shield-keyhole-line',
        featured: false,
        hours: 60,
        skills: ['Penetration Testing', 'Vulnerability Assessment', 'Ethical Hacking', 'Security Tools'],
        image: 'assets/certificates/certificates.jpg'
    },
    {
        id: 'datascience-001',
        title: 'Data Science with Python',
        issuer: 'DataCamp',
        issuerLogo: 'assets/logos/datacamp.png',
        issuerUrl: 'https://www.datacamp.com/',
        date: '2021-08-20',
        description: 'Comprehensive data science course covering Python programming, data manipulation, visualization, machine learning, and statistical analysis techniques.',
        credentialId: 'DC456789',
        verifyUrl: 'https://www.datacamp.com/certificate/DC456789',
        category: 'Data Science',
        categoryIcon: 'ri-bar-chart-box-line',
        featured: false,
        hours: 55,
        skills: ['Python', 'Pandas', 'NumPy', 'Matplotlib', 'Scikit-Learn'],
        image: 'assets/certificates/certificates.jpg'
    },
    {
        id: 'scrum-001',
        title: 'Certified Scrum Master',
        issuer: 'Scrum Alliance',
        issuerLogo: 'assets/logos/scrum-alliance.png',
        issuerUrl: 'https://www.scrumalliance.org/',
        date: '2021-05-05',
        description: 'Professional certification for Scrum Masters who facilitate, coach, and lead Agile development teams to ensure efficient implementation of Scrum methodologies.',
        credentialId: 'SA789123',
        verifyUrl: 'https://certification.scrumalliance.org/verify/SA789123',
        category: 'Project Management',
        categoryIcon: 'ri-task-line',
        featured: false,
        hours: 25,
        skills: ['Scrum', 'Agile', 'Team Facilitation', 'Project Management', 'Leadership'],
        image: 'assets/certificates/certificates.jpg'
    }
];

export default certificatesData; 